### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by q66** [chimera-linux/community#1]
We will need a logo. I am no good at graphics design so we will need someone else to make one.

Ideally it should be one that can be simplified so that it can be made into ASCII if needed.

**Comment by matu3ba** [comment]
@staalmannen The chimera is often depicted with a snake as tail and python3 will be very likely to stay as language for cports.

If one only takes the essentials (what is unlikely or painful to get swapped out), I end up with 1. LLVM (dragon in picture), 2. musl (sea shell is no animal), 3. cports in python (snake as tail not in picture).
4. Tux is penguin without wings, so that could be a pun.

GNU (the goat) is optional and I have no idea which free and open source software the lion should represent.

So from my point of view: 
1. sea shell for musl is missing
2. snake(s) (could be two snakes as the tail which are holding the sea shell) are missing.
3. The goat does not fit. Make the lion more goat-like.
4. I am very unsure about the lion, as the wings kinda remind of Pegaseus slaying the chimera. Though this could be also another pun of chimera forking Pegaseus main features or something.

**Comment by q66** [comment]
i thought about this for a while and i decided to commission an artist to do the work (and things related to it) - stuff!s currently being arranged, so stay tuned

**Comment by devenblake** [comment]
![A rough mock-up sketch described in this post](https://user-images.githubusercontent.com/26193059/148346824-04926ce8-3dba-4398-8df4-22716970f6db.png)

There hasn't been much word on a logo for the project for a short while so I very roughly sketched an idea I had. It'd be cool to map various significant components of Chimera onto a literal chimera to showcase at once what the system is and what it brings to the table. Feel free to discard, I'm aware this may be totally unneeded.
